acme_user_homepage:
    path:     /
    defaults: { _controller: AcmeUserBundle:Default:index }

acme_game_user_show:
    path: /game/{gameUserName}
    defaults: { _controller: AcmeUserBundle:Game:show }
